import React, { useState, useEffect } from 'react';
import WebsiteBuilder from '../components/builder/WebsiteBuilder';
import { generateWebsiteConfig } from '../utils/aiGenerator';
import { toast } from 'react-hot-toast';
import { useAuth } from '../context/AuthContext';
const DEFAULT_CONFIG = {
    "meta": {
        "title": "Cosmica Demo Site",
        "description": "Generated by AI"
    },
    "theme": {
        "mode": "light",
        "primary": "indigo-600",
        "secondary": "slate-900"
    },
    "sections": [
        {
            "id": "hero",
            "type": "HeroImpact",
            "content": {
                "title": "Build Your Dream Website",
                "subtitle": "Leverage the power of AI to generate stunning websites.",
                "ctaText": "Start Building"
            }
        }
    ]
};

const AIBuilderPage = () => {
    const { user, db, doc, getDoc } = useAuth();

    // State for JSON Editor
    const [jsonConfig, setJsonConfig] = useState(JSON.stringify(DEFAULT_CONFIG, null, 2));
    const [parsedConfig, setParsedConfig] = useState(DEFAULT_CONFIG);
    const [error, setError] = useState(null);
    const [isLoading, setIsLoading] = useState(true);

    // State for UI
    const [activeTab, setActiveTab] = useState('generator'); // 'editor' | 'generator'

    // State for Generator Form
    const [formData, setFormData] = useState({
        businessName: '',
        industry: 'general',
        description: '',
        style: 'impact'
    });

    // Load User Config on Mount
    useEffect(() => {
        const loadUserConfig = async () => {
            if (!user || !db) {
                setIsLoading(false); // If no user or db, stop loading immediately
                return;
            }

            try {
                const userRef = doc(db, "users", user.uid);
                const userSnap = await getDoc(userRef);

                if (userSnap.exists()) {
                    const userData = userSnap.data();

                    // 1. Load the generated website config
                    if (userData.websiteConfig) {
                        setJsonConfig(JSON.stringify(userData.websiteConfig, null, 2));
                        setParsedConfig(userData.websiteConfig);
                        toast.success("Loaded your generated website!");
                    }

                    // 2. Pre-fill the generator form with their data
                    if (userData.websiteInfo) {
                        setFormData({
                            businessName: userData.websiteInfo.domain || '',
                            industry: 'general', // We could try to map this from clientType
                            description: (userData.websiteInfo.mainService || '') + ". " + (userData.websiteInfo.uniqueAspect || ''),
                            style: 'impact' // Default
                        });
                    }
                }
            } catch (err) {
                console.error("Error loading user config:", err);
                toast.error(`Could not load config: ${err.message}`);
            } finally {
                setIsLoading(false);
            }
        };

        loadUserConfig();
    }, [user, db]);

    useEffect(() => {
        try {
            const parsed = JSON.parse(jsonConfig);
            setParsedConfig(parsed);
            setError(null);
        } catch (e) {
            setError(e.message);
        }
    }, [jsonConfig]);

    const handleGenerate = () => {
        try {
            const newConfig = generateWebsiteConfig(formData);
            setJsonConfig(JSON.stringify(newConfig, null, 2));
            toast.success("Website generated successfully!");
            // Optional: Switch to editor to show the result code
            // setActiveTab('editor'); 
        } catch (err) {
            console.error(err);
            toast.error("Failed to generate website.");
        }
    };

    const handleInputChange = (e) => {
        const { name, value } = e.target;
        setFormData(prev => ({ ...prev, [name]: value }));
    };

    return (
        <div className="flex h-screen overflow-hidden font-sans">
            {/* Left Panel: Controls */}
            <div className="w-1/3 bg-slate-900 text-white flex flex-col border-r border-slate-700 shadow-xl z-10">

                {/* Tabs */}
                <div className="flex border-b border-slate-700">
                    <button
                        onClick={() => setActiveTab('generator')}
                        className={`flex-1 py-4 text-sm font-bold uppercase tracking-wider transition-colors ${activeTab === 'generator' ? 'bg-slate-800 text-blue-400 border-b-2 border-blue-400' : 'text-slate-400 hover:text-white'}`}
                    >
                        AI Generator
                    </button>
                    <button
                        onClick={() => setActiveTab('editor')}
                        className={`flex-1 py-4 text-sm font-bold uppercase tracking-wider transition-colors ${activeTab === 'editor' ? 'bg-slate-800 text-blue-400 border-b-2 border-blue-400' : 'text-slate-400 hover:text-white'}`}
                    >
                        JSON Editor
                    </button>
                </div>

                {/* Content Area */}
                <div className="flex-1 overflow-y-auto">

                    {/* Generator Form */}
                    {activeTab === 'generator' && (
                        <div className="p-6 space-y-6 animate-fade-in">
                            <div>
                                <label className="block text-xs font-bold text-slate-400 uppercase mb-2">Business Name</label>
                                <input
                                    type="text"
                                    name="businessName"
                                    value={formData.businessName}
                                    onChange={handleInputChange}
                                    className="w-full bg-slate-800 border border-slate-700 rounded p-3 text-white focus:border-blue-500 focus:outline-none transition-colors"
                                    placeholder="e.g. Acme Corp"
                                />
                            </div>

                            <div>
                                <label className="block text-xs font-bold text-slate-400 uppercase mb-2">Industry</label>
                                <select
                                    name="industry"
                                    value={formData.industry}
                                    onChange={handleInputChange}
                                    className="w-full bg-slate-800 border border-slate-700 rounded p-3 text-white focus:border-blue-500 focus:outline-none transition-colors"
                                >
                                    <option value="general">General</option>
                                    <option value="technology">Technology & SaaS</option>
                                    <option value="health">Health & Wellness</option>
                                    <option value="legal">Legal & Finance</option>
                                    <option value="restaurant">Restaurant & Food</option>
                                </select>
                            </div>

                            <div>
                                <label className="block text-xs font-bold text-slate-400 uppercase mb-2">Description</label>
                                <textarea
                                    name="description"
                                    value={formData.description}
                                    onChange={handleInputChange}
                                    className="w-full bg-slate-800 border border-slate-700 rounded p-3 text-white focus:border-blue-500 focus:outline-none transition-colors h-32 resize-none"
                                    placeholder="Describe your business..."
                                />
                            </div>

                            <div>
                                <label className="block text-xs font-bold text-slate-400 uppercase mb-2">Visual Style</label>
                                <div className="grid grid-cols-2 gap-3">
                                    {['impact', 'cinematic', 'capture', 'elegant'].map(style => (
                                        <button
                                            key={style}
                                            onClick={() => setFormData(prev => ({ ...prev, style }))}
                                            className={`p-3 rounded border text-sm font-medium capitalize transition-all ${formData.style === style
                                                ? 'bg-blue-600 border-blue-600 text-white'
                                                : 'bg-slate-800 border-slate-700 text-slate-300 hover:border-slate-500'}`}
                                        >
                                            {style}
                                        </button>
                                    ))}
                                </div>
                            </div>

                            <button
                                onClick={handleGenerate}
                                className="w-full py-4 bg-gradient-to-r from-blue-600 to-indigo-600 text-white font-bold rounded-lg shadow-lg hover:shadow-blue-500/30 hover:scale-[1.02] transition-all transform"
                            >
                                ✨ Generate Website
                            </button>
                        </div>
                    )}

                    {/* JSON Editor */}
                    {activeTab === 'editor' && (
                        <div className="h-full flex flex-col">
                            <div className="p-2 bg-slate-800 text-xs text-slate-400 flex justify-between items-center">
                                <span>config.json</span>
                                <span className={error ? 'text-red-400' : 'text-green-400'}>
                                    {error ? 'Invalid JSON' : 'Valid'}
                                </span>
                            </div>
                            <textarea
                                className="flex-1 w-full bg-slate-900 p-4 font-mono text-sm text-green-400 focus:outline-none resize-none"
                                value={jsonConfig}
                                onChange={(e) => setJsonConfig(e.target.value)}
                                spellCheck="false"
                            />
                            {error && (
                                <div className="p-4 bg-red-900/50 text-red-200 text-xs border-t border-red-800">
                                    {error}
                                </div>
                            )}
                        </div>
                    )}
                </div>
            </div>

            {/* Right Panel: Live Preview */}
            <div className="w-2/3 bg-gray-100 overflow-y-auto relative scroll-smooth">
                <div className="sticky top-4 right-4 z-50 float-right mr-4">
                    <div className="bg-white/90 backdrop-blur px-4 py-2 rounded-full text-xs font-bold shadow-lg border border-gray-200 text-gray-600 flex items-center gap-2">
                        <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></span>
                        Live Preview
                    </div>
                </div>
                <WebsiteBuilder siteConfig={parsedConfig} />
            </div>
        </div>
    );
};

export default AIBuilderPage;
