import React, { useState, useEffect } from 'react';
import WebsiteBuilder from '../components/builder/WebsiteBuilder';

const DEFAULT_CONFIG = {
    "meta": {
        "title": "Cosmica Demo Site",
        "description": "Generated by AI"
    },
    "theme": {
        "mode": "light",
        "primary": "indigo-600",
        "secondary": "slate-900"
    },
    "sections": [
        {
            "id": "navbar",
            "type": "NavbarImpact",
            "content": {
                "logo": "Cosmica AI",
                "links": [
                    { "name": "Features", "href": "#features" },
                    { "name": "Services", "href": "#services" },
                    { "name": "Pricing", "href": "#pricing" }
                ],
                "ctaText": "Get Started"
            }
        },
        {
            "id": "hero",
            "type": "HeroImpact",
            "content": {
                "title": "Build Your Dream Website in Minutes",
                "subtitle": "Leverage the power of AI to generate stunning, high-performance websites tailored to your brand.",
                "ctaText": "Start Building Free"
            }
        },
        {
            "id": "features",
            "type": "FeaturesImpact",
            "content": {
                "title": "Why Choose Cosmica?",
                "subtitle": "We combine design excellence with AI efficiency."
            }
        },
        {
            "id": "cta",
            "type": "CTAImpact",
            "content": {
                "title": "Ready to Transform Your Online Presence?",
                "subtitle": "Join thousands of satisfied users who have built their sites with Cosmica.",
                "ctaText": "Launch Now"
            }
        },
        {
            "id": "footer",
            "type": "FooterImpact",
            "content": {
                "brand": "Cosmica AI"
            }
        }
    ]
};

const AIBuilderPage = () => {
    const [jsonConfig, setJsonConfig] = useState(JSON.stringify(DEFAULT_CONFIG, null, 2));
    const [parsedConfig, setParsedConfig] = useState(DEFAULT_CONFIG);
    const [error, setError] = useState(null);

    useEffect(() => {
        try {
            const parsed = JSON.parse(jsonConfig);
            setParsedConfig(parsed);
            setError(null);
        } catch (e) {
            setError(e.message);
        }
    }, [jsonConfig]);

    return (
        <div className="flex h-screen overflow-hidden">
            {/* Left Panel: JSON Editor */}
            <div className="w-1/3 bg-slate-900 text-white flex flex-col border-r border-slate-700">
                <div className="p-4 border-b border-slate-700 flex justify-between items-center bg-slate-800">
                    <h2 className="font-bold text-lg">AI Configuration</h2>
                    <span className={`text-xs px-2 py-1 rounded ${error ? 'bg-red-500' : 'bg-green-500'}`}>
                        {error ? 'Invalid JSON' : 'Valid'}
                    </span>
                </div>
                <div className="flex-1 relative">
                    <textarea
                        className="w-full h-full bg-slate-900 p-4 font-mono text-sm text-green-400 focus:outline-none resize-none"
                        value={jsonConfig}
                        onChange={(e) => setJsonConfig(e.target.value)}
                        spellCheck="false"
                    />
                </div>
                {error && (
                    <div className="p-4 bg-red-900/50 text-red-200 text-xs border-t border-red-800">
                        {error}
                    </div>
                )}
            </div>

            {/* Right Panel: Live Preview */}
            <div className="w-2/3 bg-gray-100 overflow-y-auto relative">
                <div className="absolute top-4 right-4 z-50 bg-white/90 backdrop-blur px-3 py-1 rounded-full text-xs font-bold shadow-sm border border-gray-200 text-gray-500">
                    Live Preview
                </div>
                <WebsiteBuilder siteConfig={parsedConfig} />
            </div>
        </div>
    );
};

export default AIBuilderPage;
